In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
import os
from biodata.bed import BEDGraphReader
import itertools
import numpy as np
import encode_utils as eu
from encode_utils.connection import Connection
from biodata.baseio import BaseReader
from collections import OrderedDict
import subprocess

In [2]:
PROJECT_DIR_d = "/fs/cbsuhy02/storage/yc2553/yc2553/projects/TRE_directionality/"

# Basic information

In [3]:
%env DCC_API_KEY=TQPAWO52
%env DCC_SECRET_KEY=lmrphzifyfdiu7ep

env: DCC_API_KEY=TQPAWO52
env: DCC_SECRET_KEY=lmrphzifyfdiu7ep

In [22]:
conn = Connection("prod", submission=True)

2024-10-22 14:58:36,375:eu_debug:	submission=True: In submission mode.

In [5]:
lab = "/labs/haiyuan-yu/"
award = "/awards/UM1HG009393/"
assembly = "GRCh38"

In [6]:
lib_names = {"C1": ["C1a", "C1b"]}
encode_ontologies = {"C1": "encode:K562"}

In [7]:
cd $PROJECT_DIR_d/PROcap

/fs/cbsuhy02/storage/yc2553/yc2553/projects/TRE_directionality/PROcap

# Document

In [44]:
header = ["document_type", "lab", "award", "attachment", "aliases"]
contents = [
			["pipeline protocol", lab, award,
			 {"path":"ENCODE_submission/20240501_PRO-cap_Computational_Pipeline.pdf"}, ["haiyuan-yu:PROcap-Pipelines2"]]
			]
df = pd.DataFrame(contents, columns=header)
df.to_csv("ENCODE_submission/submit_document.txt", sep="\t", index=False)
df

,document_type,lab,award,attachment,aliases
0,pipeline protocol,/labs/haiyuan-yu/,/awards/UM1HG009393/,{'path': 'ENCODE_submission/20240501_PRO-cap_Computational_Pipeline.pdf'},[haiyuan-yu:PROcap-Pipelines2]

In [47]:
document_logs = []
for content in contents:
	payload = OrderedDict(zip(header, content))
	payload[Connection.PROFILE_KEY] = "document"
	document_logs.append(conn.post(payload))

2024-10-18 12:39:33,924:eu_debug:
IN post().
2024-10-18 12:39:35,270:eu_debug:	<<<<<< POST document record haiyuan-yu:PROcap-Pipelines2 To DCC with URL https://www.encodeproject.org/document and this payload:

{
  "aliases": [
    "haiyuan-yu:PROcap-Pipelines2"
  ],
  "attachment": {
    "download": "20240501_PRO-cap_Computational_Pipeline.pdf",

# Experiment

In [12]:
contents =[]
header = ["lab", "award", "biosample_ontology", "assay_term_name", "description", "submitter_comment", "documents", "aliases"]
for sample_id in lib_names:
	biosample_ontology = encode_ontologies[sample_id]
	assay_term_name = "PRO-cap"
	description = f"A run-on assay that precisely maps the transcription start sites genome-wide with high sensitivity and specificity in K562 cells."
	submitter_comment = "Experiment performed by Sagar R. Shah and preprocessed by Alden Leung and You Chen"
	documents = ["haiyuan-yu:PROcap-Pipelines2", "haiyuan-yu:PROcap-Protocols"]
	aliases = [f"haiyuan-yu:procap-experiment-{sample_id}"]
	contents.append([lab, award, biosample_ontology, assay_term_name, description, submitter_comment, documents, aliases])
df = pd.DataFrame(contents, columns=header)
df.to_csv("ENCODE_submission/submit_experiment.txt", sep="\t", index=False)
df

,lab,award,biosample_ontology,assay_term_name,description,submitter_comment,documents,aliases
0,/labs/haiyuan-yu/,/awards/UM1HG009393/,encode:K562,PRO-cap,A run-on assay that precisely maps the transcription start sites genome-wide with high sensitivity and specificity in K562 cells.,Experiment performed by Sagar R. Shah and preprocessed by Alden Leung and You Chen,"[haiyuan-yu:PROcap-Pipelines2, haiyuan-yu:PROcap-Protocols]",[haiyuan-yu:procap-experiment-C1]

In [39]:
experiment_logs = []
for content in contents:
	payload = OrderedDict(zip(header, content))
	payload[Connection.PROFILE_KEY] = "experiment"
	experiment_logs.append(conn.post(payload))

2024-10-18 12:36:25,359:eu_debug:
IN post().
2024-10-18 12:36:26,547:eu_debug:	<<<<<< POST experiment record haiyuan-yu:procap-experiment-C1 To DCC with URL https://www.encodeproject.org/experiment and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-experiment-C1"
  ],
  "assay_term_name": "PRO-cap",
  "award": "/awards/UM1HG009393/",
  "biosample_ontology": "encode:K562",
  "description": "A run-on assay that precisely maps the transcription start sites genome-wide with high sensitivity and specificity in K562 cells.",
  "documents": [
    "haiyuan-yu:PROcap-Pipelines2",
    "haiyuan-yu:PROcap-Protocols"
  ],
  "lab": "/labs/haiyuan-yu/"
}


2024-10-18 12:36:26,929:eu_debug:	Success.

# Biosample

In [10]:
organism = "human"
sources = {"C1": "/sources/atcc/"}
starting_amounts = {"C1": 10e6}
starting_amount_units = "cells"
donors = {"C1": "ENCDO000AAD"}

In [11]:
contents = []
header = ["lab", "award", "aliases", "biosample_ontology", "organism", "source", "starting_amount", "starting_amount_units", "donor"]
for sample_id in lib_names:
	aliases = [f"haiyuan-yu:procap-biosample-{sample_id}"]
	contents.append([lab, award, aliases, encode_ontologies[sample_id], organism, sources[sample_id],
					 int(starting_amounts[sample_id]), starting_amount_units, donors[sample_id]
					])
df = pd.DataFrame(contents, columns=header)
df.to_csv("ENCODE_submission/submit_biosample.txt", sep="\t", index=False)
df

,lab,award,aliases,biosample_ontology,organism,source,starting_amount,starting_amount_units,donor
0,/labs/haiyuan-yu/,/awards/UM1HG009393/,[haiyuan-yu:procap-biosample-C1],encode:K562,human,/sources/atcc/,10000000,cells,ENCDO000AAD

In [12]:
biosample_logs = []
for content in contents:
	payload = OrderedDict(zip(header, content))
	payload[Connection.PROFILE_KEY] = "biosample"
	biosample_logs.append(conn.post(payload))

2024-10-18 22:32:46,045:eu_debug:
IN post().
2024-10-18 22:32:47,461:eu_debug:	<<<<<< POST biosample record haiyuan-yu:procap-biosample-C1 To DCC with URL https://www.encodeproject.org/biosample and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-biosample-C1"
  ],
  "award": "/awards/UM1HG009393/",
  "biosample_ontology": "encode:K562",
  "donor": "ENCDO000AAD",
  "lab": "/labs/haiyuan-yu/",
  "organism": "human",
  "source": "/sources/atcc/",
  "starting_amount": 10000000,
  "starting_amount_units": "cells"
}


2024-10-18 22:32:47,868:eu_debug:	{'@type': ['HTTPConflict', 'Error'], 'status': 'error', 'code': 409, 'title': 'Conflict', 'description': 'There was a conflict when trying to complete your request.', 'detail': "Keys conflict: [('alias', 'haiyuan-yu:procap-biosample-C1')]"}
2024-10-18 22:32:47,869:eu_debug:	>>>>>>GET haiyuan-yu:procap-biosample-C1 From DCC with URL https://www.encodeproject.org/haiyuan-yu:procap-biosample-C1/?format=json&datastore=database
2024-10-18 22:32:48,325:eu_debug:	Will not POST 'haiyuan-yu:procap-biosample-C1' since it already exists with aliases '['haiyuan-yu:procap-biosample-C1']'.

In [21]:
# Add a patch

payload = {
	conn.ENCID_KEY: "haiyuan-yu:procap-biosample-C1",
	"donor": "ENCDO000AAD"
	}
conn.patch(payload)

2024-10-21 21:13:15,872:eu_debug:
IN patch()
2024-10-21 21:13:15,873:eu_debug:	>>>>>>GET haiyuan-yu:procap-biosample-C1 From DCC with URL https://www.encodeproject.org/haiyuan-yu:procap-biosample-C1/?format=json&datastore=database&frame=edit
2024-10-21 21:13:16,255:eu_debug:	<<<<<< PATCHING haiyuan-yu:procap-biosample-C1 To DCC with URL https://www.encodeproject.org/haiyuan-yu:procap-biosample-C1 and this payload:

{
  "donor": "ENCDO000AAD"
}


2024-10-21 21:13:17,947:eu_debug:	Success.

{'accession': 'ENCBS165TOO',
 'aliases': ['haiyuan-yu:procap-biosample-C1'],
 'schema_version': '26',
 'status': 'in progress',
 'lab': '/labs/haiyuan-yu/',
 'award': '/awards/UM1HG009393/',
 'date_created': '2024-10-18T16:44:42.097597+00:00',
 'submitted_by': '/users/3094ca4c-d412-4cb5-b754-3ebcd95aa7e3/',
 'documents': [],
 'references': [],
 'source': '/sources/atcc/',
 'biosample_ontology': '/biosample-types/cell_line_EFO_0002067/',
 'genetic_modifications': [],
 'alternate_accessions': [],
 'treatments': [],
 'dbxrefs': [],
 'donor': '/human-donors/ENCDO000AAD/',
 'organism': '/organisms/human/',
 'internal_tags': [],
 'starting_amount': 10000000,
 'starting_amount_units': 'cells',
 '@id': '/biosamples/ENCBS165TOO/',
 '@type': ['Biosample', 'Item'],
 'uuid': '2c1c1522-e3dc-4488-a84e-7a5b318515fc',
 'sex': 'female',
 'age': '53',
 'age_units': 'year',
 'health_status': 'chronic myelogenous leukemia (CML)',
 'life_stage': 'adult',
 'applied_modifications': [],
 'characterizations': [],
 'parent_of': [],
 'age_display': '53 years',
 'origin_batch': '/biosamples/ENCBS165TOO/',
 'perturbed': False,
 'simple_summary': '',
 'summary': 'Homo sapiens K562 cell line'}

# Library

In [49]:
nucleic_acid_term_name = "RNA"
strand_specificity = "reverse"
construction_method = ["capped RNA enrichment"]
library_size_selection_method = "Streptavidin magnetic beads"

In [50]:
# RNA length

rnalens = {}
for sample_id in lib_names:
	for lib_name in lib_names[sample_id]:
		df = pd.read_table(f"{PROJECT_DIR_d}PROcap/QC/RNALen/{lib_name}_RNALen_stat.txt", header=None, index_col=0)
		rnalens[lib_name] = int(df.loc["mean"].iloc[0])

In [57]:
contents = []
header = ["lab", "award", "aliases", "nucleic_acid_term_name", "strand_specificity", "biosample", "average_fragment_size", "construction_method", "library_size_selection_method"]
for sample_id in lib_names:
	biosample = encode_ontologies[sample_id].split(":")[1]
	for lib_name in lib_names[sample_id]:
		biological_replicate_number = 1
		technical_replicate_number = lib_names[sample_id].index(lib_name)+1
		aliases = [f"haiyuan-yu:procap-library-{sample_id}-{biological_replicate_number}_{technical_replicate_number}"]
		biosample = f"haiyuan-yu:procap-biosample-{sample_id}"
		average_fragment_size = rnalens[lib_name]
		contents.append([lab, award, aliases, nucleic_acid_term_name, strand_specificity, biosample, average_fragment_size, construction_method, library_size_selection_method])
df = pd.DataFrame(contents, columns=header)
df.to_csv("ENCODE_submission/submit_library.txt", sep="\t", index=False)
df

,lab,award,aliases,nucleic_acid_term_name,strand_specificity,biosample,average_fragment_size,construction_method,library_size_selection_method
0,/labs/haiyuan-yu/,/awards/UM1HG009393/,[haiyuan-yu:procap-library-C1-1_1],RNA,reverse,haiyuan-yu:procap-biosample-C1,42,[capped RNA enrichment],Streptavidin magnetic beads
1,/labs/haiyuan-yu/,/awards/UM1HG009393/,[haiyuan-yu:procap-library-C1-1_2],RNA,reverse,haiyuan-yu:procap-biosample-C1,42,[capped RNA enrichment],Streptavidin magnetic beads

In [58]:
library_logs = []
for content in contents:
	payload = OrderedDict(zip(header, content))
	payload[Connection.PROFILE_KEY] = "library"
	library_logs.append(conn.post(payload))

2024-10-18 12:45:58,703:eu_debug:
IN post().
2024-10-18 12:45:58,705:eu_debug:	<<<<<< POST library record haiyuan-yu:procap-library-C1-1_1 To DCC with URL https://www.encodeproject.org/library and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-library-C1-1_1"
  ],
  "average_fragment_size": 42,
  "award": "/awards/UM1HG009393/",
  "biosample": "haiyuan-yu:procap-biosample-C1",
  "construction_method": [
    "capped RNA enrichment"
  ],
  "lab": "/labs/haiyuan-yu/",
  "library_size_selection_method": "Streptavidin magnetic beads",
  "nucleic_acid_term_name": "RNA",
  "strand_specificity": "reverse"
}


2024-10-18 12:45:59,108:eu_debug:	Success.
2024-10-18 12:45:59,110:eu_debug:
IN post().
2024-10-18 12:45:59,111:eu_debug:	<<<<<< POST library record haiyuan-yu:procap-library-C1-1_2 To DCC with URL https://www.encodeproject.org/library and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-library-C1-1_2"
  ],
  "average_fragment_size": 42,
  "award": "/awards/UM1HG009393/",
  "biosample": "haiyuan-yu:procap-biosample-C1",
  "construction_method": [
    "capped RNA enrichment"
  ],
  "lab": "/labs/haiyuan-yu/",
  "library_size_selection_method": "Streptavidin magnetic beads",
  "nucleic_acid_term_name": "RNA",
  "strand_specificity": "reverse"
}


2024-10-18 12:45:59,457:eu_debug:	Success.

# Replicate

In [59]:
contents = []
header = ["aliases", "experiment", "biological_replicate_number", "technical_replicate_number", "library"]
for sample_id in lib_names:
	experiment = f"haiyuan-yu:procap-experiment-{sample_id}"
	for lib_name in lib_names[sample_id]:
		biological_replicate_number = 1
		technical_replicate_number = lib_names[sample_id].index(lib_name)+1
		suffix = f"{sample_id}-{biological_replicate_number}_{technical_replicate_number}"
		library = f"haiyuan-yu:procap-library-{suffix}"
		aliases = [f"haiyuan-yu:procap-replicate-{suffix}"]
		contents.append([aliases, experiment, biological_replicate_number, technical_replicate_number, library])
df = pd.DataFrame(contents, columns=header)
df.to_csv("ENCODE_submission/submit_replicate.txt", sep="\t", index=False)
df

,aliases,experiment,biological_replicate_number,technical_replicate_number,library
0,[haiyuan-yu:procap-replicate-C1-1_1],haiyuan-yu:procap-experiment-C1,1,1,haiyuan-yu:procap-library-C1-1_1
1,[haiyuan-yu:procap-replicate-C1-1_2],haiyuan-yu:procap-experiment-C1,1,2,haiyuan-yu:procap-library-C1-1_2

In [61]:
replicate_logs = []
for content in contents:
	payload = OrderedDict(zip(header, content))
	payload[Connection.PROFILE_KEY] = "replicate"
	replicate_logs.append(conn.post(payload))

2024-10-18 12:46:45,137:eu_debug:
IN post().
2024-10-18 12:46:45,138:eu_debug:	<<<<<< POST replicate record haiyuan-yu:procap-replicate-C1-1_1 To DCC with URL https://www.encodeproject.org/replicate and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-replicate-C1-1_1"
  ],
  "biological_replicate_number": 1,
  "experiment": "haiyuan-yu:procap-experiment-C1",
  "library": "haiyuan-yu:procap-library-C1-1_1",
  "technical_replicate_number": 1
}


2024-10-18 12:46:45,496:eu_debug:	Success.
2024-10-18 12:46:45,498:eu_debug:
IN post().
2024-10-18 12:46:45,499:eu_debug:	<<<<<< POST replicate record haiyuan-yu:procap-replicate-C1-1_2 To DCC with URL https://www.encodeproject.org/replicate and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-replicate-C1-1_2"
  ],
  "biological_replicate_number": 1,
  "experiment": "haiyuan-yu:procap-experiment-C1",
  "library": "haiyuan-yu:procap-library-C1-1_2",
  "technical_replicate_number": 2
}


2024-10-18 12:46:45,870:eu_debug:	Success.

# File

## fastq

In [62]:
def get_read_length(f):
	with BaseReader(f) as br:
		br.read()
		s1 = br.read()
		br.read()
		s2 = br.read()
		if len(s1) != len(s2):
			raise Exception()
		return len(s1)

In [63]:
procap_info = pd.read_excel(f"{PROJECT_DIR_d}output/supp_tables/suppTable1.xlsx")

In [64]:
run_type = "paired-ended"
platform = "encode:NovaSeq6000"
file_format = "fastq"
output_type = "reads"

contents = []
header = ["lab", "award", "dataset", "file_format", "run_type", "platform", "output_type", "replicate", "submitted_file_name", "paired_end", "paired_with", "aliases", "read_length"]
for sample_id in lib_names:
	dataset = f"haiyuan-yu:procap-experiment-{sample_id}"
	for lib_name in lib_names[sample_id]:
		biological_replicate_number = 1
		technical_replicate_number = lib_names[sample_id].index(lib_name)+1
		replicate = f"haiyuan-yu:procap-replicate-{sample_id}-{biological_replicate_number}_{technical_replicate_number}"
		for row in procap_info.loc[procap_info["Library Name"] == lib_name].iterrows():
			r1, r2 = "RawData/" + row[1]["Sequencing Read 1"], "RawData/" + row[1]["Sequencing Read 2"]
			suffix = f"{sample_id}-{biological_replicate_number}_{technical_replicate_number}"
			submitted_file_name = r1
			paired_end = "1"
			paired_with = ""
			aliases = [f"haiyuan-yu:procap-read1-{suffix}"]
			read_length = get_read_length(r1)
			contents.append([lab, award, dataset, file_format, run_type, platform, output_type, replicate, submitted_file_name, paired_end, paired_with, aliases, read_length])

			submitted_file_name = r2 
			paired_end = "2"
			paired_with = f"haiyuan-yu:procap-read1-{suffix}"
			aliases = [f"haiyuan-yu:procap-read2-{suffix}"]
			read_length = get_read_length(r2)
			contents.append([lab, award, dataset, file_format, run_type, platform, output_type, replicate, submitted_file_name, paired_end, paired_with, aliases, read_length])
df = pd.DataFrame(contents, columns=header)
df.to_csv("ENCODE_submission/submit_file_fastq.txt", sep="\t", index=False)
df

,lab,award,dataset,file_format,run_type,platform,output_type,replicate,submitted_file_name,paired_end,paired_with,aliases,read_length
0,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,fastq,paired-ended,encode:NovaSeq6000,reads,haiyuan-yu:procap-replicate-C1-1_1,RawData/C1a_CKDL220028609-1A_HLJNNDSX5_L4_1.fq.gz,1,,[haiyuan-yu:procap-read1-C1-1_1],150
1,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,fastq,paired-ended,encode:NovaSeq6000,reads,haiyuan-yu:procap-replicate-C1-1_1,RawData/C1a_CKDL220028609-1A_HLJNNDSX5_L4_2.fq.gz,2,haiyuan-yu:procap-read1-C1-1_1,[haiyuan-yu:procap-read2-C1-1_1],150
2,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,fastq,paired-ended,encode:NovaSeq6000,reads,haiyuan-yu:procap-replicate-C1-1_2,RawData/C1b_CKDL220028609-1A_HLJNNDSX5_L4_1.fq.gz,1,,[haiyuan-yu:procap-read1-C1-1_2],150
3,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,fastq,paired-ended,encode:NovaSeq6000,reads,haiyuan-yu:procap-replicate-C1-1_2,RawData/C1b_CKDL220028609-1A_HLJNNDSX5_L4_2.fq.gz,2,haiyuan-yu:procap-read1-C1-1_2,[haiyuan-yu:procap-read2-C1-1_2],150

In [65]:
file_logs = []
for content in contents:
	payload = OrderedDict(zip(header, content))
	if payload["paired_with"] == '':
		payload.pop('paired_with')
	payload[Connection.PROFILE_KEY] = "file"
	file_logs.append(conn.post(payload))

2024-10-18 12:47:46,584:eu_debug:
IN post().
2024-10-18 12:47:56,987:eu_debug:	<<<<<< POST file record haiyuan-yu:procap-read1-C1-1_1 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-read1-C1-1_1"
  ],
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "file_format": "fastq",
  "file_size": 3653430197,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "eff7508909da3bf4cc86bb77b4184213",
  "output_type": "reads",
  "paired_end": "1",
  "platform": "encode:NovaSeq6000",
  "read_length": 150,
  "replicate": "haiyuan-yu:procap-replicate-C1-1_1",
  "run_type": "paired-ended",
  "submitted_file_name": "RawData/C1a_CKDL220028609-1A_HLJNNDSX5_L4_1.fq.gz"
}


2024-10-18 12:47:57,819:eu_debug:	Success.
2024-10-18 12:47:57,820:eu_debug:
IN upload_file()

2024-10-18 12:47:57,821:eu_debug:	Attempting to generate new file upload credentials
2024-10-18 12:47:58,494:eu_debug:	Success: upload credentials for 'ENCFF298PQK' regenerated.
2024-10-18 12:47:58,496:eu_debug:	>>>>>>GET ENCFF298PQK From DCC with URL https://www.encodeproject.org/ENCFF298PQK/?format=json&datastore=database
2024-10-18 12:47:59,033:eu_debug:	Running command 'aws s3 cp RawData/C1a_CKDL220028609-1A_HLJNNDSX5_L4_1.fq.gz s3://encode-files/2024/10/18/a7ee2578-7b7b-49e9-a8eb-bb1b45ffb9eb/ENCFF298PQK.fastq.gz'.
2024-10-18 12:48:55,044:eu_debug:	AWS upload successful.
2024-10-18 12:48:55,048:eu_debug:
IN post().
2024-10-18 12:49:03,910:eu_debug:	<<<<<< POST file record haiyuan-yu:procap-read2-C1-1_1 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-read2-C1-1_1"
  ],
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "file_format": "fastq",
  "file_size": 4502525199,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "a619c3ab3fb98c9ca61dd7fbf4a69848",
  "output_type": "reads",
  "paired_end": "2",
  "paired_with": "haiyuan-yu:procap-read1-C1-1_1",
  "platform": "encode:NovaSeq6000",
  "read_length": 150,
  "replicate": "haiyuan-yu:procap-replicate-C1-1_1",
  "run_type": "paired-ended",
  "submitted_file_name": "RawData/C1a_CKDL220028609-1A_HLJNNDSX5_L4_2.fq.gz"
}


2024-10-18 12:49:04,740:eu_debug:	Success.
2024-10-18 12:49:04,742:eu_debug:
IN upload_file()

2024-10-18 12:49:04,742:eu_debug:	Attempting to generate new file upload credentials
2024-10-18 12:49:05,464:eu_debug:	Success: upload credentials for 'ENCFF084GIA' regenerated.
2024-10-18 12:49:05,466:eu_debug:	>>>>>>GET ENCFF084GIA From DCC with URL https://www.encodeproject.org/ENCFF084GIA/?format=json&datastore=database
2024-10-18 12:49:06,001:eu_debug:	Running command 'aws s3 cp RawData/C1a_CKDL220028609-1A_HLJNNDSX5_L4_2.fq.gz s3://encode-files/2024/10/18/2b4f2156-446f-4574-a879-0da8062c7923/ENCFF084GIA.fastq.gz'.
2024-10-18 12:49:38,111:eu_debug:	AWS upload successful.
2024-10-18 12:49:38,115:eu_debug:
IN post().
2024-10-18 12:49:48,941:eu_debug:	<<<<<< POST file record haiyuan-yu:procap-read1-C1-1_2 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-read1-C1-1_2"
  ],
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "file_format": "fastq",
  "file_size": 3928888157,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "081f4fbbbfd35abbf8bb689c63343678",
  "output_type": "reads",
  "paired_end": "1",
  "platform": "encode:NovaSeq6000",
  "read_length": 150,
  "replicate": "haiyuan-yu:procap-replicate-C1-1_2",
  "run_type": "paired-ended",
  "submitted_file_name": "RawData/C1b_CKDL220028609-1A_HLJNNDSX5_L4_1.fq.gz"
}


2024-10-18 12:49:49,754:eu_debug:	Success.
2024-10-18 12:49:49,755:eu_debug:
IN upload_file()

2024-10-18 12:49:49,756:eu_debug:	Attempting to generate new file upload credentials
2024-10-18 12:49:50,460:eu_debug:	Success: upload credentials for 'ENCFF191TQL' regenerated.
2024-10-18 12:49:50,462:eu_debug:	>>>>>>GET ENCFF191TQL From DCC with URL https://www.encodeproject.org/ENCFF191TQL/?format=json&datastore=database
2024-10-18 12:49:51,024:eu_debug:	Running command 'aws s3 cp RawData/C1b_CKDL220028609-1A_HLJNNDSX5_L4_1.fq.gz s3://encode-files/2024/10/18/3462b979-fcc5-49e9-9c9f-1b90630c7ec2/ENCFF191TQL.fastq.gz'.
2024-10-18 12:50:19,585:eu_debug:	AWS upload successful.
2024-10-18 12:50:19,589:eu_debug:
IN post().
2024-10-18 12:50:29,263:eu_debug:	<<<<<< POST file record haiyuan-yu:procap-read2-C1-1_2 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-read2-C1-1_2"
  ],
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "file_format": "fastq",
  "file_size": 4432030669,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "f2f80d7f8fcbc9707adae8fbae516db8",
  "output_type": "reads",
  "paired_end": "2",
  "paired_with": "haiyuan-yu:procap-read1-C1-1_2",
  "platform": "encode:NovaSeq6000",
  "read_length": 150,
  "replicate": "haiyuan-yu:procap-replicate-C1-1_2",
  "run_type": "paired-ended",
  "submitted_file_name": "RawData/C1b_CKDL220028609-1A_HLJNNDSX5_L4_2.fq.gz"
}


2024-10-18 12:50:30,022:eu_debug:	Success.
2024-10-18 12:50:30,024:eu_debug:
IN upload_file()

2024-10-18 12:50:30,024:eu_debug:	Attempting to generate new file upload credentials
2024-10-18 12:50:30,714:eu_debug:	Success: upload credentials for 'ENCFF583FVG' regenerated.
2024-10-18 12:50:30,716:eu_debug:	>>>>>>GET ENCFF583FVG From DCC with URL https://www.encodeproject.org/ENCFF583FVG/?format=json&datastore=database
2024-10-18 12:50:31,292:eu_debug:	Running command 'aws s3 cp RawData/C1b_CKDL220028609-1A_HLJNNDSX5_L4_2.fq.gz s3://encode-files/2024/10/18/567e2117-6e20-4816-b3bd-a05ad0260651/ENCFF583FVG.fastq.gz'.
2024-10-18 12:51:01,743:eu_debug:	AWS upload successful.

## bam (unfiltered alignments)

In [66]:
step_run = "haiyuan-yu:pro-cap-run-step-1"
file_format = "bam"
output_type = "unfiltered alignments"

contents = []
header = ["lab", "award", "dataset", "file_format", "output_type", "submitted_file_name", "aliases", "derived_from", "assembly", "step_run"]
for sample_id in lib_names:
	dataset = f"haiyuan-yu:procap-experiment-{sample_id}"
	for lib_name in lib_names[sample_id]:
		biological_replicate_number = 1
		technical_replicate_number = lib_names[sample_id].index(lib_name)+1
		suffix = f"{sample_id}-{biological_replicate_number}_{technical_replicate_number}"
		aliases = [f"haiyuan-yu:test-procap-unfiltered_alignment-{suffix}"]
		derived_from = ["john-lis:procap-rdna", "dnanexus:file-BjB0pV00Qy5PzkzfX1Gy6pYy",
						f"haiyuan-yu:procap-read1-{suffix}",
						f"haiyuan-yu:procap-read2-{suffix}"
						]
		submitted_file_name = f"RawAlignments/{lib_name}_Aligned.sortedByCoord.out.bam"
		contents.append([lab, award, dataset, file_format, output_type, submitted_file_name, aliases, derived_from, assembly, step_run])
df = pd.DataFrame(contents, columns=header)
df.to_csv("ENCODE_submission/submit_file_unfiltered_alignment.txt", sep="\t", index=False)
df

,lab,award,dataset,file_format,output_type,submitted_file_name,aliases,derived_from,assembly,step_run
0,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,bam,unfiltered alignments,RawAlignments/C1a_Aligned.sortedByCoord.out.bam,[haiyuan-yu:test-procap-unfiltered_alignment-C1-1_1],"[john-lis:procap-rdna, dnanexus:file-BjB0pV00Qy5PzkzfX1Gy6pYy, haiyuan-yu:procap-read1-C1-1_1, haiyuan-yu:procap-read2-C1-1_1]",GRCh38,haiyuan-yu:pro-cap-run-step-1
1,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,bam,unfiltered alignments,RawAlignments/C1b_Aligned.sortedByCoord.out.bam,[haiyuan-yu:test-procap-unfiltered_alignment-C1-1_2],"[john-lis:procap-rdna, dnanexus:file-BjB0pV00Qy5PzkzfX1Gy6pYy, haiyuan-yu:procap-read1-C1-1_2, haiyuan-yu:procap-read2-C1-1_2]",GRCh38,haiyuan-yu:pro-cap-run-step-1

In [67]:
file_logs = []
for content in contents:
	payload = OrderedDict(zip(header, content))
	payload[Connection.PROFILE_KEY] = "file"
	file_logs.append(conn.post(payload))

2024-10-18 12:51:38,627:eu_debug:
IN post().
2024-10-18 12:51:43,380:eu_debug:	<<<<<< POST file record haiyuan-yu:test-procap-unfiltered_alignment-C1-1_1 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:test-procap-unfiltered_alignment-C1-1_1"
  ],
  "assembly": "GRCh38",
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "derived_from": [
    "john-lis:procap-rdna",
    "dnanexus:file-BjB0pV00Qy5PzkzfX1Gy6pYy",
    "haiyuan-yu:procap-read1-C1-1_1",
    "haiyuan-yu:procap-read2-C1-1_1"
  ],
  "file_format": "bam",
  "file_size": 2809589420,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "6799ad1e6deedff22cb7782c8ab781dd",
  "output_type": "unfiltered alignments",
  "step_run": "haiyuan-yu:pro-cap-run-step-1",
  "submitted_file_name": "RawAlignments/C1a_Aligned.sortedByCoord.out.bam"
}


2024-10-18 12:51:44,204:eu_debug:	Success.
2024-10-18 12:51:44,206:eu_debug:
IN upload_file()

2024-10-18 12:51:44,206:eu_debug:	Attempting to generate new file upload credentials
2024-10-18 12:51:44,881:eu_debug:	Success: upload credentials for 'ENCFF155YEA' regenerated.
2024-10-18 12:51:44,883:eu_debug:	>>>>>>GET ENCFF155YEA From DCC with URL https://www.encodeproject.org/ENCFF155YEA/?format=json&datastore=database
2024-10-18 12:51:45,732:eu_debug:	Running command 'aws s3 cp RawAlignments/C1a_Aligned.sortedByCoord.out.bam s3://encode-files/2024/10/18/5a60040f-1d9d-4785-989f-1c352ff201f9/ENCFF155YEA.bam'.
2024-10-18 12:52:06,255:eu_debug:	AWS upload successful.
2024-10-18 12:52:06,259:eu_debug:
IN post().
2024-10-18 12:52:12,810:eu_debug:	<<<<<< POST file record haiyuan-yu:test-procap-unfiltered_alignment-C1-1_2 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:test-procap-unfiltered_alignment-C1-1_2"
  ],
  "assembly": "GRCh38",
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "derived_from": [
    "john-lis:procap-rdna",
    "dnanexus:file-BjB0pV00Qy5PzkzfX1Gy6pYy",
    "haiyuan-yu:procap-read1-C1-1_2",
    "haiyuan-yu:procap-read2-C1-1_2"
  ],
  "file_format": "bam",
  "file_size": 2721167121,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "1e53bfe1b8456682b23b3c6d24d3a35b",
  "output_type": "unfiltered alignments",
  "step_run": "haiyuan-yu:pro-cap-run-step-1",
  "submitted_file_name": "RawAlignments/C1b_Aligned.sortedByCoord.out.bam"
}


2024-10-18 12:52:13,533:eu_debug:	Success.
2024-10-18 12:52:13,534:eu_debug:
IN upload_file()

2024-10-18 12:52:13,535:eu_debug:	Attempting to generate new file upload credentials
2024-10-18 12:52:14,267:eu_debug:	Success: upload credentials for 'ENCFF131OEV' regenerated.
2024-10-18 12:52:14,269:eu_debug:	>>>>>>GET ENCFF131OEV From DCC with URL https://www.encodeproject.org/ENCFF131OEV/?format=json&datastore=database
2024-10-18 12:52:15,003:eu_debug:	Running command 'aws s3 cp RawAlignments/C1b_Aligned.sortedByCoord.out.bam s3://encode-files/2024/10/18/6fe8184f-3f14-4370-a0f9-c72c7808240e/ENCFF131OEV.bam'.
2024-10-18 12:52:33,334:eu_debug:	AWS upload successful.

## bam (alignments)

In [70]:
step_run = "haiyuan-yu:pro-cap-run-step-2"
file_format = "bam"
output_type = "alignments"

contents = []
header = ["lab", "award", "dataset", "file_format", "output_type", "submitted_file_name", "aliases", "derived_from", "assembly", "step_run"]
for sample_id in lib_names:
	dataset = f"haiyuan-yu:procap-experiment-{sample_id}"
	for lib_name in lib_names[sample_id]:
		biological_replicate_number = 1
		technical_replicate_number = lib_names[sample_id].index(lib_name)+1
		suffix = f"{sample_id}-{biological_replicate_number}_{technical_replicate_number}"
		aliases = [f"haiyuan-yu:procap-alignment-{suffix}"]
		derived_from = [f"haiyuan-yu:test-procap-unfiltered_alignment-{suffix}"]
		submitted_file_name = f"RawAlignments/{lib_name}_dedup.bam"
		contents.append([lab, award, dataset, file_format, output_type, submitted_file_name, aliases, derived_from, assembly, step_run])
df = pd.DataFrame(contents, columns=header)
df.to_csv("ENCODE_submission/submit_file_alignment.txt", sep="\t", index=False)
df

,lab,award,dataset,file_format,output_type,submitted_file_name,aliases,derived_from,assembly,step_run
0,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,bam,alignments,RawAlignments/C1a_dedup.bam,[haiyuan-yu:procap-alignment-C1-1_1],[haiyuan-yu:test-procap-unfiltered_alignment-C1-1_1],GRCh38,haiyuan-yu:pro-cap-run-step-2
1,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,bam,alignments,RawAlignments/C1b_dedup.bam,[haiyuan-yu:procap-alignment-C1-1_2],[haiyuan-yu:test-procap-unfiltered_alignment-C1-1_2],GRCh38,haiyuan-yu:pro-cap-run-step-2

In [71]:
file_logs = []
for content in contents:
	payload = OrderedDict(zip(header, content))
	payload[Connection.PROFILE_KEY] = "file"
	file_logs.append(conn.post(payload))

2024-10-18 12:55:39,999:eu_debug:
IN post().
2024-10-18 12:55:42,215:eu_debug:	<<<<<< POST file record haiyuan-yu:procap-alignment-C1-1_1 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-alignment-C1-1_1"
  ],
  "assembly": "GRCh38",
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "derived_from": [
    "haiyuan-yu:test-procap-unfiltered_alignment-C1-1_1"
  ],
  "file_format": "bam",
  "file_size": 1361141151,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "2d1c607f6735869c3b7289a8e90631f0",
  "output_type": "alignments",
  "step_run": "haiyuan-yu:pro-cap-run-step-2",
  "submitted_file_name": "RawAlignments/C1a_dedup.bam"
}


2024-10-18 12:55:43,054:eu_debug:	Success.
2024-10-18 12:55:43,055:eu_debug:
IN upload_file()

2024-10-18 12:55:43,056:eu_debug:	Attempting to generate new file upload credentials
2024-10-18 12:55:43,785:eu_debug:	Success: upload credentials for 'ENCFF633JKZ' regenerated.
2024-10-18 12:55:43,787:eu_debug:	>>>>>>GET ENCFF633JKZ From DCC with URL https://www.encodeproject.org/ENCFF633JKZ/?format=json&datastore=database
2024-10-18 12:55:44,515:eu_debug:	Running command 'aws s3 cp RawAlignments/C1a_dedup.bam s3://encode-files/2024/10/18/f0402f99-2f75-4ac6-98f5-0f29edd2357f/ENCFF633JKZ.bam'.
2024-10-18 12:55:55,571:eu_debug:	AWS upload successful.
2024-10-18 12:55:55,574:eu_debug:
IN post().
2024-10-18 12:55:58,746:eu_debug:	<<<<<< POST file record haiyuan-yu:procap-alignment-C1-1_2 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-alignment-C1-1_2"
  ],
  "assembly": "GRCh38",
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "derived_from": [
    "haiyuan-yu:test-procap-unfiltered_alignment-C1-1_2"
  ],
  "file_format": "bam",
  "file_size": 1318078494,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "9244dee4b95eb92edaf4a2b757799206",
  "output_type": "alignments",
  "step_run": "haiyuan-yu:pro-cap-run-step-2",
  "submitted_file_name": "RawAlignments/C1b_dedup.bam"
}


2024-10-18 12:55:59,506:eu_debug:	Success.
2024-10-18 12:55:59,507:eu_debug:
IN upload_file()

2024-10-18 12:55:59,508:eu_debug:	Attempting to generate new file upload credentials
2024-10-18 12:56:00,197:eu_debug:	Success: upload credentials for 'ENCFF082TEE' regenerated.
2024-10-18 12:56:00,199:eu_debug:	>>>>>>GET ENCFF082TEE From DCC with URL https://www.encodeproject.org/ENCFF082TEE/?format=json&datastore=database
2024-10-18 12:56:00,867:eu_debug:	Running command 'aws s3 cp RawAlignments/C1b_dedup.bam s3://encode-files/2024/10/18/ff1705dc-0e2c-4f3a-b34b-aa62b9e81397/ENCFF082TEE.bam'.
2024-10-18 12:56:11,245:eu_debug:	AWS upload successful.

## bigwig

In [72]:
step_run = "haiyuan-yu:pro-cap-run-step-3"
file_format = "bigWig"

header = ["lab", "award", "dataset", "file_format", "output_type", "submitted_file_name", "aliases", "derived_from", "assembly", "step_run"]
contents = []

for sample_id in lib_names:
	dataset = f"haiyuan-yu:procap-experiment-{sample_id}"
	for lib_name in lib_names[sample_id]:
		biological_replicate_number = 1
		technical_replicate_number = lib_names[sample_id].index(lib_name)+1
		suffix = f"{sample_id}-{biological_replicate_number}_{technical_replicate_number}"
		derived_from = [f"haiyuan-yu:procap-alignment-{suffix}"]
		
		output_type = "plus strand signal of unique reads"
		aliases = [f"haiyuan-yu:procap-bigwig-plus-{suffix}"]
		submitted_file_name=f"Alignments/{lib_name}_5pl.bw"
		contents.append([lab, award, dataset, file_format, output_type, submitted_file_name, aliases, derived_from, assembly, step_run])
		
		output_type = "minus strand signal of unique reads"
		aliases = [f"haiyuan-yu:procap-bigwig-minus-{suffix}"]
		submitted_file_name = f"Alignments/{lib_name}_5mn.bw"
		contents.append([lab, award, dataset, file_format, output_type, submitted_file_name, aliases, derived_from, assembly, step_run])
df = pd.DataFrame(contents, columns=header)
df.to_csv("ENCODE_submission/submit_file_bigwig_patch.txt", sep="\t", index=False)
df

,lab,award,dataset,file_format,output_type,submitted_file_name,aliases,derived_from,assembly,step_run
0,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,bigWig,plus strand signal of unique reads,Alignments/C1a_5pl.bw,[haiyuan-yu:procap-bigwig-plus-C1-1_1],[haiyuan-yu:procap-alignment-C1-1_1],GRCh38,haiyuan-yu:pro-cap-run-step-3
1,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,bigWig,minus strand signal of unique reads,Alignments/C1a_5mn.bw,[haiyuan-yu:procap-bigwig-minus-C1-1_1],[haiyuan-yu:procap-alignment-C1-1_1],GRCh38,haiyuan-yu:pro-cap-run-step-3
2,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,bigWig,plus strand signal of unique reads,Alignments/C1b_5pl.bw,[haiyuan-yu:procap-bigwig-plus-C1-1_2],[haiyuan-yu:procap-alignment-C1-1_2],GRCh38,haiyuan-yu:pro-cap-run-step-3
3,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,bigWig,minus strand signal of unique reads,Alignments/C1b_5mn.bw,[haiyuan-yu:procap-bigwig-minus-C1-1_2],[haiyuan-yu:procap-alignment-C1-1_2],GRCh38,haiyuan-yu:pro-cap-run-step-3

In [73]:
file_logs = []
for content in contents:
	payload = OrderedDict(zip(header, content))
	payload[Connection.PROFILE_KEY] = "file"
	file_logs.append(conn.post(payload))

2024-10-18 12:56:21,314:eu_debug:
IN post().
2024-10-18 12:56:21,432:eu_debug:	<<<<<< POST file record haiyuan-yu:procap-bigwig-plus-C1-1_1 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-bigwig-plus-C1-1_1"
  ],
  "assembly": "GRCh38",
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "derived_from": [
    "haiyuan-yu:procap-alignment-C1-1_1"
  ],
  "file_format": "bigWig",
  "file_size": 15556338,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "ba96e2c7f78e92d50de70d490f35fece",
  "output_type": "plus strand signal of unique reads",
  "step_run": "haiyuan-yu:pro-cap-run-step-3",
  "submitted_file_name": "Alignments/C1a_5pl.bw"
}


2024-10-18 12:56:22,177:eu_debug:	Success.
2024-10-18 12:56:22,178:eu_debug:
IN upload_file()

2024-10-18 12:56:22,178:eu_debug:	Attempting to generate new file upload credentials
2024-10-18 12:56:22,882:eu_debug:	Success: upload credentials for 'ENCFF850NZE' regenerated.
2024-10-18 12:56:22,884:eu_debug:	>>>>>>GET ENCFF850NZE From DCC with URL https://www.encodeproject.org/ENCFF850NZE/?format=json&datastore=database
2024-10-18 12:56:23,684:eu_debug:	Running command 'aws s3 cp Alignments/C1a_5pl.bw s3://encode-files/2024/10/18/b31d5ca0-1c15-4140-89a5-46c44f4a0fed/ENCFF850NZE.bigWig'.
2024-10-18 12:56:26,790:eu_debug:	AWS upload successful.
2024-10-18 12:56:26,794:eu_debug:
IN post().
2024-10-18 12:56:26,885:eu_debug:	<<<<<< POST file record haiyuan-yu:procap-bigwig-minus-C1-1_1 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-bigwig-minus-C1-1_1"
  ],
  "assembly": "GRCh38",
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "derived_from": [
    "haiyuan-yu:procap-alignment-C1-1_1"
  ],
  "file_format": "bigWig",
  "file_size": 15403214,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "e44864d97ef95447f0db0fce7c74c481",
  "output_type": "minus strand signal of unique reads",
  "step_run": "haiyuan-yu:pro-cap-run-step-3",
  "submitted_file_name": "Alignments/C1a_5mn.bw"
}


2024-10-18 12:56:27,621:eu_debug:	Success.
2024-10-18 12:56:27,623:eu_debug:
IN upload_file()

2024-10-18 12:56:27,623:eu_debug:	Attempting to generate new file upload credentials
2024-10-18 12:56:28,307:eu_debug:	Success: upload credentials for 'ENCFF364CCA' regenerated.
2024-10-18 12:56:28,309:eu_debug:	>>>>>>GET ENCFF364CCA From DCC with URL https://www.encodeproject.org/ENCFF364CCA/?format=json&datastore=database
2024-10-18 12:56:28,955:eu_debug:	Running command 'aws s3 cp Alignments/C1a_5mn.bw s3://encode-files/2024/10/18/91cbdb67-37b8-4aad-a88e-1eb8417ee82f/ENCFF364CCA.bigWig'.
2024-10-18 12:56:31,934:eu_debug:	AWS upload successful.
2024-10-18 12:56:31,938:eu_debug:
IN post().
2024-10-18 12:56:32,019:eu_debug:	<<<<<< POST file record haiyuan-yu:procap-bigwig-plus-C1-1_2 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-bigwig-plus-C1-1_2"
  ],
  "assembly": "GRCh38",
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "derived_from": [
    "haiyuan-yu:procap-alignment-C1-1_2"
  ],
  "file_format": "bigWig",
  "file_size": 15690043,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "331b09e24b7ffd86fe7236835ee512f9",
  "output_type": "plus strand signal of unique reads",
  "step_run": "haiyuan-yu:pro-cap-run-step-3",
  "submitted_file_name": "Alignments/C1b_5pl.bw"
}


2024-10-18 12:56:32,772:eu_debug:	Success.
2024-10-18 12:56:32,773:eu_debug:
IN upload_file()

2024-10-18 12:56:32,773:eu_debug:	Attempting to generate new file upload credentials
2024-10-18 12:56:33,438:eu_debug:	Success: upload credentials for 'ENCFF918QKQ' regenerated.
2024-10-18 12:56:33,440:eu_debug:	>>>>>>GET ENCFF918QKQ From DCC with URL https://www.encodeproject.org/ENCFF918QKQ/?format=json&datastore=database
2024-10-18 12:56:34,122:eu_debug:	Running command 'aws s3 cp Alignments/C1b_5pl.bw s3://encode-files/2024/10/18/2ab85fe2-f8e4-4fea-b653-9ede44d3dc33/ENCFF918QKQ.bigWig'.
2024-10-18 12:56:36,784:eu_debug:	AWS upload successful.
2024-10-18 12:56:36,788:eu_debug:
IN post().
2024-10-18 12:56:36,852:eu_debug:	<<<<<< POST file record haiyuan-yu:procap-bigwig-minus-C1-1_2 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-bigwig-minus-C1-1_2"
  ],
  "assembly": "GRCh38",
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "derived_from": [
    "haiyuan-yu:procap-alignment-C1-1_2"
  ],
  "file_format": "bigWig",
  "file_size": 15539373,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "8b2ac129f66d98730d75e884a15ab48b",
  "output_type": "minus strand signal of unique reads",
  "step_run": "haiyuan-yu:pro-cap-run-step-3",
  "submitted_file_name": "Alignments/C1b_5mn.bw"
}


2024-10-18 12:56:37,616:eu_debug:	Success.
2024-10-18 12:56:37,617:eu_debug:
IN upload_file()

2024-10-18 12:56:37,618:eu_debug:	Attempting to generate new file upload credentials
2024-10-18 12:56:38,311:eu_debug:	Success: upload credentials for 'ENCFF861JFD' regenerated.
2024-10-18 12:56:38,312:eu_debug:	>>>>>>GET ENCFF861JFD From DCC with URL https://www.encodeproject.org/ENCFF861JFD/?format=json&datastore=database
2024-10-18 12:56:39,022:eu_debug:	Running command 'aws s3 cp Alignments/C1b_5mn.bw s3://encode-files/2024/10/18/659e8cd0-db2e-41d5-8318-305b82842660/ENCFF861JFD.bigWig'.
2024-10-18 12:56:41,299:eu_debug:	AWS upload successful.

## bed

In [21]:
# Bed files are expected to be gzipped for data submission

for sample_id in lib_names:
	slibs = [lib_name for lib_name in lib_names[sample_id]]
	files = [f"Peaks/PINTS/brm_{'_and_'.join(slibs)}_erm_1_{k}_peaks.bed" for k in ["bidirectional", "divergent", "unidirectional"]]
	for f in files:
		gf = f + ".gz"
		subprocess.run(["gzip", "-c", f], stdout=open(gf, 'wb'))

In [19]:
step_run = "haiyuan-yu:pro-cap-run-step-4"
file_format = "bed"
file_format_type = "bed3+"

contents = []
header = ["lab", "award", "dataset", "file_format", "file_format_type", "output_type", "submitted_file_name", "aliases", "derived_from", "assembly", "step_run"]
for sample_id in lib_names:
	dataset=f"haiyuan-yu:procap-experiment-{sample_id}"
	suffice = []
	slibs = []
	for lib_name in lib_names[sample_id]:
		biological_replicate_number = 1
		technical_replicate_number = lib_names[sample_id].index(lib_name)+1
		slibs.append(lib_name)
		suffice.append(f"{sample_id}-{biological_replicate_number}_{technical_replicate_number}")
	derived_from = ([f"haiyuan-yu:procap-bigwig-plus-{suffix}" for suffix in suffice]
					+ [f"haiyuan-yu:procap-bigwig-minus-{suffix}" for suffix in suffice])

	output_type = "bidirectional peaks"
	output_type_str = "bidirectional_peaks"
	aliases = [f"haiyuan-yu:procap-{output_type_str}-{sample_id}"]
	submitted_file_name=f"Peaks/PINTS/brm_{'_and_'.join(slibs)}_erm_1_bidirectional_peaks.bed.gz"
	contents.append([lab, award, dataset, file_format, file_format_type, output_type, submitted_file_name, aliases, derived_from, assembly, step_run])

	output_type = "unidirectional peaks"
	output_type_str = "unidirectional_peaks"
	aliases = [f"haiyuan-yu:procap-{output_type_str}-{sample_id}"]
	submitted_file_name=f"Peaks/PINTS/brm_{'_and_'.join(slibs)}_erm_1_unidirectional_peaks.bed.gz"
	contents.append([lab, award, dataset, file_format, file_format_type, output_type, submitted_file_name, aliases, derived_from, assembly, step_run])

df = pd.DataFrame(contents, columns=header)
df.to_csv("ENCODE_submission/submit_file_bed.txt", sep="\t", index=False)
df

,lab,award,dataset,file_format,file_format_type,output_type,submitted_file_name,aliases,derived_from,assembly,step_run
0,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,bed,bed3+,bidirectional peaks,Peaks/PINTS/brm_C1a_and_C1b_erm_1_bidirectional_peaks.bed.gz,[haiyuan-yu:procap-bidirectional_peaks-C1],"[haiyuan-yu:procap-bigwig-plus-C1-1_1, haiyuan-yu:procap-bigwig-plus-C1-1_2, haiyuan-yu:procap-bigwig-minus-C1-1_1, haiyuan-yu:procap-bigwig-minus-C1-1_2]",GRCh38,haiyuan-yu:pro-cap-run-step-4
1,/labs/haiyuan-yu/,/awards/UM1HG009393/,haiyuan-yu:procap-experiment-C1,bed,bed3+,unidirectional peaks,Peaks/PINTS/brm_C1a_and_C1b_erm_1_unidirectional_peaks.bed.gz,[haiyuan-yu:procap-unidirectional_peaks-C1],"[haiyuan-yu:procap-bigwig-plus-C1-1_1, haiyuan-yu:procap-bigwig-plus-C1-1_2, haiyuan-yu:procap-bigwig-minus-C1-1_1, haiyuan-yu:procap-bigwig-minus-C1-1_2]",GRCh38,haiyuan-yu:pro-cap-run-step-4

In [26]:
file_logs = []
for content in contents:
	payload = OrderedDict(zip(header, content))
	payload[Connection.PROFILE_KEY] = "file"
	file_logs.append(conn.post(payload))

2024-10-18 22:52:27,138:eu_debug:
IN post().
2024-10-18 22:52:27,140:eu_debug:	<<<<<< POST file record haiyuan-yu:procap-bidirectional_peaks-C1 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-bidirectional_peaks-C1"
  ],
  "assembly": "GRCh38",
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "derived_from": [
    "haiyuan-yu:procap-bigwig-plus-C1-1_1",
    "haiyuan-yu:procap-bigwig-plus-C1-1_2",
    "haiyuan-yu:procap-bigwig-minus-C1-1_1",
    "haiyuan-yu:procap-bigwig-minus-C1-1_2"
  ],
  "file_format": "bed",
  "file_format_type": "bed3+",
  "file_size": 574642,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "a420954d40dbc4a96082a4cc5d61fd10",
  "output_type": "bidirectional peaks",
  "step_run": "haiyuan-yu:pro-cap-run-step-4",
  "submitted_file_name": "Peaks/PINTS/brm_C1a_and_C1b_erm_1_bidirectional_peaks.bed.gz"
}


2024-10-18 22:52:27,849:eu_debug:	{'@type': ['HTTPConflict', 'Error'], 'status': 'error', 'code': 409, 'title': 'Conflict', 'description': 'There was a conflict when trying to complete your request.', 'detail': "Keys conflict: [('alias', 'haiyuan-yu:procap-bidirectional_peaks-C1')]"}
2024-10-18 22:52:27,850:eu_debug:	>>>>>>GET haiyuan-yu:procap-bidirectional_peaks-C1 From DCC with URL https://www.encodeproject.org/haiyuan-yu:procap-bidirectional_peaks-C1/?format=json&datastore=database
2024-10-18 22:52:28,539:eu_debug:	Will not POST 'haiyuan-yu:procap-bidirectional_peaks-C1' since it already exists with aliases '['haiyuan-yu:procap-bidirectional_peaks-C1']'.
2024-10-18 22:52:28,541:eu_debug:
IN post().
2024-10-18 22:52:28,543:eu_debug:	<<<<<< POST file record haiyuan-yu:procap-unidirectional_peaks-C1 To DCC with URL https://www.encodeproject.org/file and this payload:

{
  "aliases": [
    "haiyuan-yu:procap-unidirectional_peaks-C1"
  ],
  "assembly": "GRCh38",
  "award": "/awards/UM1HG009393/",
  "dataset": "haiyuan-yu:procap-experiment-C1",
  "derived_from": [
    "haiyuan-yu:procap-bigwig-plus-C1-1_1",
    "haiyuan-yu:procap-bigwig-plus-C1-1_2",
    "haiyuan-yu:procap-bigwig-minus-C1-1_1",
    "haiyuan-yu:procap-bigwig-minus-C1-1_2"
  ],
  "file_format": "bed",
  "file_format_type": "bed3+",
  "file_size": 431085,
  "lab": "/labs/haiyuan-yu/",
  "md5sum": "e3da913d92594dc094624952d41c34ca",
  "output_type": "unidirectional peaks",
  "step_run": "haiyuan-yu:pro-cap-run-step-4",
  "submitted_file_name": "Peaks/PINTS/brm_C1a_and_C1b_erm_1_unidirectional_peaks.bed.gz"
}


2024-10-18 22:52:29,311:eu_debug:	Success.
2024-10-18 22:52:29,312:eu_debug:
IN upload_file()

2024-10-18 22:52:29,313:eu_debug:	Attempting to generate new file upload credentials
2024-10-18 22:52:30,029:eu_debug:	Success: upload credentials for 'ENCFF963WTD' regenerated.
2024-10-18 22:52:30,031:eu_debug:	>>>>>>GET ENCFF963WTD From DCC with URL https://www.encodeproject.org/ENCFF963WTD/?format=json&datastore=database
2024-10-18 22:52:30,728:eu_debug:	Running command 'aws s3 cp Peaks/PINTS/brm_C1a_and_C1b_erm_1_unidirectional_peaks.bed.gz s3://encode-files/2024/10/19/5ed2cdcd-cacc-4ab8-9e9f-cb9132fc6dff/ENCFF963WTD.bed.gz'.
2024-10-18 22:53:07,221:eu_debug:	AWS upload successful.

In [23]:
# Re-upload the file

conn.upload_file(file_id="ENCFF051LUE",file_path=f"Peaks/PINTS/brm_{'_and_'.join(slibs)}_erm_1_bidirectional_peaks.bed.gz")

2024-10-22 15:00:03,682:eu_debug:
IN upload_file()

2024-10-22 15:00:03,683:eu_debug:	Attempting to generate new file upload credentials
2024-10-22 15:00:05,084:eu_debug:	Success: upload credentials for 'ENCFF051LUE' regenerated.
2024-10-22 15:00:05,085:eu_debug:	>>>>>>GET ENCFF051LUE From DCC with URL https://www.encodeproject.org/ENCFF051LUE/?format=json&datastore=database
2024-10-22 15:00:06,085:eu_debug:	Running command 'aws s3 cp Peaks/PINTS/brm_C1a_and_C1b_erm_1_bidirectional_peaks.bed.gz s3://encode-files/2024/10/18/d745a3cb-20e2-452e-a8c2-f87de9de5854/ENCFF051LUE.bed.gz'.
2024-10-22 15:00:59,983:eu_debug:	AWS upload successful.